name = "MaterialModelsTesting"
uuid = "882b014b-b96c-4115-8629-e17fb35110d2"
authors = ["Knut Andreas Meyer and contributors"]
version = "0.1.0"

[deps]
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MaterialModelsBase = "af893363-701d-44dc-8b1e-d9a2c129bfc9"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
FiniteDiff = "2.28.1"
ForwardDiff = "1.1.0"
LinearAlgebra = "1.11.0"
StaticArrays = "1.9.15"
Tensors = "1.16.2"
Test = "1.11.0"
julia = "1.10"

[sources]
MaterialModelsBase = {url = "https://github.com/KnutAM/MaterialModelsBase.jl"}

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
